import pandas as pd
import os
import re

from snakemake.utils import min_version

# Set minimum Snakemake version
min_version('6.0')

# Set some predetermined values
configfile:
    'config/config.yaml'

SAMPLES = pd.read_table(config['samples'], dtype=str).set_index(['sample'], drop=False)
BISCUIT_INDEX_FORMATS = ['bis.ann', 'bis.amb', 'par.bwt', 'dau.bwt', 'bis.pac', 'par.sa', 'dau.sa', 'fai']

def set_output_directory():
    if config['output_directory'] == '':
        return os.getcwd()
    else:
        return config['output_directory']
output_directory = set_output_directory()

rule all:
    input:
        ## Preprocessing files
        # Rename FASTQs and run FastQC run over them
        expand(
            f'{output_directory}/analysis/raw_fastqc/{{samples.sample}}-1-R{{read}}_fastqc.{{ext}}',
            ext=['html','zip'], read=[1,2], samples=SAMPLES.itertuples()
        ),

        # fastq_screen
        expand(
            f'{output_directory}/analysis/fastq_screen/{{samples.sample}}-1-R{{read}}_screen.html',
            read=[1,2], samples=SAMPLES.itertuples()
        ) if config['run_fastq_screen'] else [],

        ## Run BISCUIT
        # biscuit align
        expand(
            f'{output_directory}/analysis/align/{{samples.sample}}.sorted.markdup.bam',
            samples=SAMPLES.itertuples()
        ),
        # biscuit mergecg
        expand(
            f'{output_directory}/analysis/pileup/{{samples.sample}}_mergecg.bed.gz',
            samples=SAMPLES.itertuples()
        ),
        # biscuit vcf2bed -t snp
        expand(
            f'{output_directory}/analysis/snps/{{samples.sample}}.snp.bed.gz',
            samples=SAMPLES.itertuples()
        ) if config['generate_snps'] or config['epiread'] else [],
        # biscuit epiread
        expand(
            f'{output_directory}/analysis/epiread/{{samples.sample}}.epibed.gz',
            samples=SAMPLES.itertuples()
        ) if config['epiread'] else [],

        ## Do post-processing QC
        # MultiQC
        f'{output_directory}/analysis/multiqc/multiqc_report.html',


# Rules for preprocessing files
include:
    'rules/preprocessing.smk'

# Rules for running BISCUIT related commands
include:
    'rules/biscuit.smk'

# Rules for various QC metrics
include:
    'rules/qc.smk'
